#!/bin/sh
set -e

TAR_FILE="/tmp/properties.tar.gz"
RELEASES_URL="https://github.com/OpusCapita/properties/releases"

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" |
    rev |
    cut -f1 -d'/'|
    rev
}

download() {
  test -z "$VERSION" && VERSION="$(last_version)"
  test -z "$VERSION" && {
    echo "Unable to get properties version." >&2
    exit 1
  }
  rm -f "$TAR_FILE"
  curl -s -L -o "$TAR_FILE" \
    "$RELEASES_URL/download/$VERSION/properties_$(uname -s)_$(uname -m).tar.gz"
}

download
test -z "$TARGET_DIR" && TARGET_DIR="$(mktemp -d)"
tar -xf "$TAR_FILE" -C "$TARGET_DIR"
if [ -n "$*" ]
then
  "${TARGET_DIR}/properties" "$@"
else
  echo "File 'properties' is installed/extracted into '$TARGET_DIR' folder"
fi
