#!/bin/sh
set -e

TAR_FILE="/tmp/properties.tar.gz"
RELEASES_URL="https://github.com/OpusCapita/properties/releases"

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" |
    rev |
    cut -f1 -d'/'|
    rev
}

download() {
  test -z "$PROPERTIES_VERSION" && PROPERTIES_VERSION="$(last_version)"
  test -z "$PROPERTIES_VERSION" && {
    echo "Unable to get properties version." >&2
    exit 1
  }
  rm -f "$TAR_FILE"
  curl -s -L -o "$TAR_FILE" \
    "$RELEASES_URL/download/$PROPERTIES_VERSION/properties_$(uname -s)_$(uname -m).tar.gz"
}

download
test -z "$PROPERTIES_TARGET_DIR" && PROPERTIES_TARGET_DIR="$(mktemp -d)"
# extracting only 'properties' file
tar -xf "$TAR_FILE" -C "$PROPERTIES_TARGET_DIR" properties
if [ -n "$*" ]
then
  "${PROPERTIES_TARGET_DIR}/properties" "$@"
else
  echo "File 'properties' is installed/extracted into '$PROPERTIES_TARGET_DIR' folder"
fi
